services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9872:9872"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9872"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongodb
    environment:
      - PORT=${PORT}
      - MONGO_URI=mongodb://mongodb:27017/aevr-wallet
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_LOGO=${MAIL_LOGO}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI}
      - APP_URL=${APP_URL}
      - APP_NAME=${APP_NAME}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - PAY_API_KEY=${PAY_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DEFAULT_MAIL_PROVIDER=${DEFAULT_MAIL_PROVIDER}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
